
# ----- Right Arm -----
right_arm_chain:
  settler_config:  /right_arm_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - /r2/right_arm/joint0
        - /r2/right_arm/joint1
        - /r2/right_arm/joint2
        - /r2/right_arm/joint3
        - /r2/right_arm/joint4
        tolerances:
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        max_step:   1.0
        cache_size: 1500


# ----- Left Arm -----
left_arm_chain:
  settler_config:  /left_arm_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - /r2/left_arm/joint0
        - /r2/left_arm/joint1
        - /r2/left_arm/joint2
        - /r2/left_arm/joint3
        - /r2/left_arm/joint4
        tolerances:
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        max_step:   1.0
        cache_size: 1500

# ----- Head -----
head_chain:
  settler_config:  /head_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - /r2/neck/joint0
        - /r2/neck/joint1
        - /r2/neck/joint2
        tolerances:
        - 0.002
        - 0.002
        - 0.002
        max_step:   1.0
        cache_size: 1500

